# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Rhondene's Blog
description: Welcome to my blog! Throughout my learning journey I have benefitted immensely from blogposts and free online resources. Each one, teach one. So this is my way to pay it forward while improvinmy my writing through iteration. Here, I will share programming/bioinformatics skills I have learnt, and even neat tricks I picked up along the way."People grow through experience if they meet life honestly and courageously. This is how character is built." Eleanor Roosevelt
github_username: rhondene_wint 

# Email and twitter are optional:
email: rhondenewint93@gmail.com
twitter_username: @RWinty

# Set this to true to get LaTeX math equation support
use_math: true

# Add your Google Analytics ID here if you have one and want to use it
google_analytics:

# Everything below here can be ignored, unless you want to change the theme entirely
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
